(window.webpackJsonp=window.webpackJsonp||[]).push([[10],{tEX2:function(e,t,n){"use strict";n.r(t),n.d(t,"_frontmatter",(function(){return s})),n.d(t,"default",(function(){return d}));var r=n("IKa1"),a=n("Yh9w"),o=(n("r0ML"),n("V0Ug")),i=n("sN0p");n("xH0s");const c=["components"],s={};void 0!==s&&s&&s===Object(s)&&Object.isExtensible(s)&&!Object.prototype.hasOwnProperty.call(s,"__filemeta")&&Object.defineProperty(s,"__filemeta",{configurable:!0,value:{name:"_frontmatter",filename:"src/docs/exceptions.mdx"}});const l={_frontmatter:s},p=i.a;function d(e){let{components:t}=e,n=Object(a.a)(e,c);return Object(o.b)(p,Object(r.a)({},l,n,{components:t,mdxType:"MDXLayout"}),Object(o.b)("h1",{id:"exceptions-and-handlers"},"Exceptions and Handlers"),Object(o.b)("h2",{id:"exceptions"},"Exceptions"),Object(o.b)("p",null,"Custom Exceptions can be created by extending the HttpException class from ",Object(o.b)("inlineCode",{parentName:"p"},"core")," package. The ",Object(o.b)("inlineCode",{parentName:"p"},"HttpException")," takes following properties,"),Object(o.b)("ul",null,Object(o.b)("li",{parentName:"ul"},"statusCode: The HTTP status code of the exception"),Object(o.b)("li",{parentName:"ul"},"message: The message of the exception"),Object(o.b)("li",{parentName:"ul"},"name: The name of the exception"),Object(o.b)("li",{parentName:"ul"},"isOperational: The isOperational flag determines whether the error is operational and if the error message can be forwarded to the end user.")),Object(o.b)("h3",{id:"creating-a-custom-exception"},"Creating a custom exception"),Object(o.b)("pre",null,Object(o.b)("code",{parentName:"pre",className:"language-javascript"},"class UnauthorizedException extends HttpException {\n    constructor(message = 'You are not authorized') {\n        super(\n            401,\n            message,\n            'Unauthorized',\n            true // isOperational\n        );\n    }\n}\n")),Object(o.b)("p",null,"The given example creates an Unauthorized exception. The isOperational flag is set to true, meaning, the error message 'You are not authorized' will be passed along to the response. For errors with isOperational flag set to false, a default error message of 'Something went wrong' could be passed or an error HTML page could be rendered."),Object(o.b)("h2",{id:"exception-handlers"},"Exception Handlers"),Object(o.b)("p",null,"Exception Handlers can be created by extending the ",Object(o.b)("inlineCode",{parentName:"p"},"ExceptionHandler")," abstract class from ",Object(o.b)("inlineCode",{parentName:"p"},"core")," package. The ExceptionHandler abstract class requires a handle method to be implemented. Exception handlers are registered during the server startup process."),Object(o.b)("h3",{id:"creating-an-exception-handler"},"Creating an exception handler"),Object(o.b)("pre",null,Object(o.b)("code",{parentName:"pre",className:"language-javascript"},"\nclass UnauthorizedExceptionHandler extends ExceptionHandler {\n    public handle(\n        error: HttpException,\n        req: Request,\n        res: Response,\n        next: NextFunction\n    ): void {\n        if (error.statusCode !== 401) {\n            return next(error); // Pass the error to the next error handler\n        }\n        req.flash('error', error.message);\n        return res.redirect('/auth/login');\n    }\n}\n\n")),Object(o.b)("h3",{id:"regitering-the-handler"},"Regitering the handler"),Object(o.b)("pre",null,Object(o.b)("code",{parentName:"pre",className:"language-javascript"},"server.startup(Number(ServerConfig.PORT), {\n    name: 'CMS Server',\n    // ... other configurations\n    exceptionHandlers: [\n        new UnauthorizedExceptionHandler(),\n        new UnprocessableEntityExceptionHandler(),\n        new GlobalExceptionHandler(), // GlobalExceptionHandler should be kept at the end of the list;\n    ],\n});\n")),Object(o.b)("p",null,"In above example, three exception handlers have been registered. Note how ",Object(o.b)("inlineCode",{parentName:"p"},"new GlobalExceptionHandler()")," is kept at the end of the list. Since errors are passed from one handler to the next, if none of the handlers contain the logic to handle the current exception, it is handled by the ",Object(o.b)("inlineCode",{parentName:"p"},"GlobalExceptionHandler"),"."))}void 0!==d&&d&&d===Object(d)&&Object.isExtensible(d)&&!Object.prototype.hasOwnProperty.call(d,"__filemeta")&&Object.defineProperty(d,"__filemeta",{configurable:!0,value:{name:"MDXContent",filename:"src/docs/exceptions.mdx"}}),d.isMDXComponent=!0}}]);
//# sourceMappingURL=component---src-docs-exceptions-mdx-5f28a754e543734c083c.js.map